[vendor]
simple_model = "ollama"
complex_model = "ollama"
embeddings_model = "ollama"

[aws]
simple_model = "anthropic.claude-3-haiku-20240307-v1:0"
complex_model = "anthropic.claude-3-5-sonnet-20240620-v1:0"
embeddings_model = "amazon.titan-embed-text-v1"
region_name = "us-east-1"

[openai]
simple_model = "gpt-4o-mini"
complex_model = "gpt-4o"
embeddings_model = "text-embedding-ada-002"
base_url = "https://api.openai.com/v1/"

[ollama]
base_url = "http://10.147.19.232:11434"
simple_model = "qwen3"
complex_model = "qwen3"
embeddings_model = "qwen3-embedding:0.6b"

[tracing]
project = "rai"

[tracing.langfuse]
use_langfuse = false
host = "https://cloud.langfuse.com"

[tracing.langsmith]
use_langsmith = false
host = "https://api.smith.langchain.com"

[asr]
recording_device_name = "default"
transcription_model = "LocalWhisper"
language = "en"
vad_model = "SileroVAD"
silence_grace_period = 0.3
vad_threshold = 0.3
use_wake_word = false
wake_word_model = ""
wake_word_threshold = 0.5
wake_word_model_name = ""
transcription_model_name = "tiny"

[tts]
vendor = "ElevenLabs"
voice = ""
speaker_device_name = "default"
