[project]
name = "bandu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.9.6",
    "langchain-mcp-adapters>=0.2.0",
    "rai-core>=2.6.0",
    "rai-whoami>=0.0.5",
]
